renamed_menu_xml_ids = (
    (
        "cooperator.menu_main_easy_my_coop",
        "cooperator.menu_cooperator_main",
    ),
    (
        "cooperator.menu_easy_my_coop_main_subscription",
        "cooperator.menu_cooperator_main_subscription",
    ),
    (
        "cooperator.menu_easy_my_coop_subscription_request",
        "cooperator.menu_cooperator_subscription_request",
    ),
    (
        "cooperator.menu_easy_my_coop_cooperator_candidate",
        "cooperator.menu_cooperator_cooperator_candidate",
    ),
    (
        "cooperator.menu_easy_my_coop_subscription_register",
        "cooperator.menu_cooperator_subscription_register",
    ),
    (
        "cooperator.menu_easy_my_coop_operation_request",
        "cooperator.menu_cooperator_operation_request",
    ),
    (
        "cooperator.menu_easy_my_coop_main_coop",
        "cooperator.menu_cooperator_main_coop",
    ),
    (
        "cooperator.menu_easy_my_coop_cooperator",
        "cooperator.menu_cooperator_cooperator",
    ),
    (
        "cooperator.menu_easy_my_coop_company_representative",
        "cooperator.menu_cooperator_company_representative",
    ),
    (
        "cooperator.menu_easy_my_coop_main_reporting",
        "cooperator.menu_cooperator_main_reporting",
    ),
    (
        "cooperator.menu_easy_my_coop_config",
        "cooperator.menu_cooperator_config",
    ),
    (
        "cooperator.menu_easy_my_coop_share_product",
        "cooperator.menu_cooperator_share_product",
    ),
    (
        "cooperator.menu_easy_my_coop_templates",
        "cooperator.menu_cooperator_templates",
    ),
)
