# Do NOT update manually; changes here will be overwritten by Copier
_commit: v2.1.10
_src_path: https://github.com/coopiteasy/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 12.0
org_name: Coop IT Easy SC
org_slug: coopiteasy
rebel_module_groups: []
repo_description: This project aims to deal with modules related to cooperative management.
repo_name: Vertical Cooperative
repo_slug: vertical-cooperative
repo_website: https://coopiteasy.be
travis_apt_packages: []
travis_apt_sources: []

