# Do NOT update manually; changes here will be overwritten by Copier
_commit: v2.0.6
_src_path: https://github.com/coopiteasy/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Coop IT Easy SCRLfs
org_slug: coopiteasy
rebel_module_groups: []
repo_description: This project aim to deal with modules related to cooperatives management.
repo_name: Vertical Cooperative
repo_slug: vertical-cooperative
repo_website: https://coopiteasy.be
travis_apt_packages: []
travis_apt_sources: []
