# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.1-13-g8b8df74
_src_path: gh:coopiteasy/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 12.0
rebel_module_groups: []
repo_description: This project aim to deal with modules related to cooperatives management.
repo_name: Vertical Cooperative
repo_slug: vertical-cooperative
travis_apt_packages: []
travis_apt_sources: []
