name: Run pre-commit tests

on:
  push:
    branches:
      - 12.0
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Run pre-commit against all files
        uses: pre-commit/action@v2.0.3
